import = ["/home/re/.config/alacritty/themes/themes/palenight.toml"]

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style= "Regular"

[window]
opacity = 0.90

[window.dimensions]
columns = 130
lines = 37

